# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_unit_pathway'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('tag__name', 'pathway'),
            },
        ),
        migrations.AlterModelOptions(
            name='pathway',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='pathwaytag',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pathway'),
        ),
        migrations.AddField(
            model_name='pathwaytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tag'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='_tags',
            field=models.ManyToManyField(through='core.PathwayTag', to='core.Tag'),
        ),
    ]
