# Dockerfile

FROM ubuntu:20.04

ENV VIRTUAL_ENV=/blockstore/venv

RUN apt-get update
RUN apt-get install libmysqlclient-dev libjpeg-dev libssl-dev libffi-dev python3 python3-venv python3-pip git -y

RUN python3.8 -m venv $VIRTUAL_ENV

RUN echo 'cd /blockstore/app/' > ~/.bashrc.new
RUN echo 'export PATH=$VIRTUAL_ENV/bin:$PATH' >> ~/.bashrc.new
RUN cat ~/.bashrc >> ~/.bashrc.new
RUN mv ~/.bashrc.new ~/.bashrc
