# Dockerfile for dev.

FROM python:3.6-alpine

ENV VENV_PATH=/blockstore/venv

RUN apk update && apk upgrade
RUN apk add bash bash-completion build-base git perl

RUN python3.6 -m venv $VENV_PATH

RUN echo 'cd /blockstore/app/' >> ~/.bashrc
RUN echo 'export PATH=$VENV_PATH/bin:$PATH' >> ~/.bashrc
