# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0002_auto_20180820_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
