# Generated by Django 3.2.18 on 2023-03-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bundles', '0003_update_character_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', related_query_name='bundle', to='bundles.collection'),
        ),
    ]
