# Generated by Django 2.2.24 on 2021-08-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagstore_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tag',
            name='taxonomy',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
