# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagstore_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tagstore_django.Entity'),
        ),
    ]
